"""empty message

Revision ID: b5a658af4ce7
Revises: 
Create Date: 2022-07-23 21:51:19.281770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Enum, String
from sqlalchemy.dialects.postgresql import UUID, BYTEA
from uuid import uuid4

# revision identifiers, used by Alembic.
revision = "b5a658af4ce7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.create_table(
        "users",
        Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            default=uuid4,
            unique=True,
            nullable=False,
        ),
        Column("avatar", BYTEA()),
        Column("sex", Enum("man", "woman", name="sex__")),  # пол
        Column("first_name", String()),
        Column("last_name", String()),
        Column("email", String(), unique=True, nullable=False),
        Column("password", String(), nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
