version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBIT_PORT_1}:${RABBIT_PORT_1}
      - ${RABBIT_PORT_2}:${RABBIT_PORT_2}
    volumes:
      - rabbitmq_data:/data

  postgres:
    container_name: postgres
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env

  dating_site:
    container_name: dating
    build:
      context: /dating_site
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

  rpc:
    container_name: rpc
    build:
      context: /rpc
      dockerfile: dockerfile_rpc
    command: [ 'python','run.py' ]
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  nginx:
    container_name: nginx_dating
    build: ./nginx
    volumes:
      - ./nginx:/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - rabbitmq
      - postgres
      - dating_site

volumes:
  rabbitmq_data:
  postgres_volume:
