version: "3"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

  rpc:
    container_name: rpc
    build: .
    command: [ 'python','run.py' ]
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

volumes:
  rabbitmq_data: