FROM python:3.10.4-slim-buster
WORKDIR dating_site
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV UVICORN_ARGS "src.settings:app --host dating_site --port 8000 --workers 3"

RUN pip install --upgrade pip  --no-cache-dir
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD uvicorn $UVICORN_ARGS